
<section>		<!--Body-->
<div class="tempmargin">
</div>

<div id="content">		<!--content-->

<div class="televisionbg">
<span class="television"></span>
<span class="player"></span>
</div>

<div id="signupform">

<div class="signup">
<h2>Sign up for free <span class="orcolor"> or </span></h2> 
<input type="submit" class="connect" value="Connect with Facebook" /><br />
<p class="parastyle">Join now for FREE and we'll give you a buck just</p>

</div>

<hr / class="signuphr">

<div class="formargintop">
<div class="formlabels">
<label> Full Name:</label><br />
<label>Email Address:</label><br />
<label>Password:</label><br />
<label>Zip Code:</label><br />
</div>

<div class="forminputs">
<?php 
	echo $this->form;
?>

</div>

<div class="chkboxp">
<p>Send me newsletters. You can unsubscribe at anytime</p>
</div>



</div>
</div>

<div class="tempbox">

<div class="humanimg">
<span class="humanbg"></span>
<p>We have over <br /><a href="#">3 million members</a><br /> and more each<br /> day...</p>
</div>

<div class="coinsimg">
<span class="coinsbg"></span>
<p>We have given over<br /> <a href="#">$3 million</a><br /> and counting in rewards</p>
</div>

<div class="giftsimg">
<span class="giftbg"></span>
<p>Special offer <br /> for <br /><a href="#">Members</a></p>
</div>
</div>


<div class="blackopsbox">

<div class="callofduty blackopsline">
<h2>CALL OF DUTY: BLACKOPS II</h2>
<span></span>
</div>

<div class="getitnow">
<h2>Want to win Call of Duty: Black OPS II for FREE?<br />
	It's simple! just enter the raffle for your chance to win!</h2>
<p><strong>Platform:</strong> XBOX360</p>
<p><strong>NOTE:</strong> This item will be a pre-order.</p>
<p><strong>Release Date:</strong> November 13, 2012</p>
<p>Pushing the boundaries of whats fans have come to expect from the record-setting entertainment franchise,<br />
Call of Duty: Black Ops II propels players into a near future, 21st Century Cold War, where technology and<br />weapons
have converged to create a new generation of warfarer</p>

<div class="time">
<h2>Time Left:<span>21D 05:44:28</span></h2>
<button type="submit">GET IT NOW</button>
</div>

</div>

</div>

<div class="social">

<div class="money">
<h2>See Who Is Making Money!</h2>

<div class="photo">
<h3> ANNA POSTED A PHOTO OF THEIR $30.80</h3>
<a href="#">Check Now!</a>
<hr /> 
</div>

<div class="photo">
<h3> ANNA POSTED A PHOTO OF THEIR $30.80</h3>
<a href="#">Check Now!</a>
<hr /> 
</div>

<div class="photo">
<h3> ANNA POSTED A PHOTO OF THEIR $30.80</h3>
<a href="#">Check Now!</a>
</div>

</div>

<div class="socialmedia">
<h2>Socialise With Us!</h2>
<p>To know more about us, Socialize with us</p>
<a href="#" class="twitter"></a>
<a href="#" class="facebook"></a>
</div>

</div>

</div>		<!--Content closed-->
</section>		<!--Body closed-->


