<footer>
<div class="footerstyle">
<div class="copyright">
<p>&copy;2012 ComTesk.com</p>
<nav>
<ul>
<li class="line"><a href="#">Terms of service&nbsp;</a></li>
<li><a href="#">Privacy policy</a></li>
</ul>
</nav>
</div>

<div class="footernav">
<nav>
<ul>
<li class="line"><a href="#">SIGNUP&nbsp;&nbsp;</a></li>
<li class="line"><a href="#">FORUM&nbsp;&nbsp;</a></li>
<li class="line"><a href="#">HOW IT WORKS&nbsp;&nbsp;</a></li>
<li class="line"><a href="#">CONTACT&nbsp;&nbsp;</a></li>
<li><a href="#">TESTIMONIALS&nbsp;&nbsp;</a></li>
</ul>
</nav>
</div>

</div>

</footer>


</body>
</html>