<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Comtesk.com</title>
<link rel="stylesheet" href="/css/style.css" type="text/css" />
<link href='http://fonts.googleapis.com/css?family=Pontano+Sans' rel='stylesheet' type='text/css'>
</head>

<body>

<header>		<!--header-->

<div id="head">

<div class="logo">
<h2>Com<span>Tesk</span></h2>
<p>Earn money online</p>
</div>

<div class="headnav">
<div class="topnav">
<nav>
<ul>

<li class="line"><a href="user/index/" class="logincolor">Login</a>&nbsp;</li>
<li><a href="#" class="signupcolor">Sign up</a></li>.
<li><input type="submit" class="facebookimg" value="login" /></li>
</ul>
</nav>
</div>

<div class="mainnav">
<nav>
<ul>

<li><a href="#">Home</a></li>
<li><a href="#">Testimonial</a></li>
<li><a href="#">Forum</a></li>
<li><a href="#">Community</a></li>
<li><a href="#">Help</a></li>
<li><a href="#">Tutorials</a></li>
</ul>
</nav>
</div>

</div>
</div>

</header>		<!--Header closed-->